interface Schema0 {
  order?: (('DEFINITION' | 'LIST_RENDERING' | 'CONDITIONALS' | 'RENDER_MODIFIERS' | 'GLOBAL' | 'UNIQUE' | 'SLOT' | 'TWO_WAY_BINDING' | 'OTHER_DIRECTIVES' | 'OTHER_ATTR' | 'ATTR_STATIC' | 'ATTR_DYNAMIC' | 'ATTR_SHORTHAND_BOOL' | 'EVENTS' | 'CONTENT') | ('DEFINITION' | 'LIST_RENDERING' | 'CONDITIONALS' | 'RENDER_MODIFIERS' | 'GLOBAL' | 'UNIQUE' | 'SLOT' | 'TWO_WAY_BINDING' | 'OTHER_DIRECTIVES' | 'OTHER_ATTR' | 'ATTR_STATIC' | 'ATTR_DYNAMIC' | 'ATTR_SHORTHAND_BOOL' | 'EVENTS' | 'CONTENT')[])[]
  alphabetical?: boolean
}

export type AttributesOrderRuleOptions = [Schema0]
